name: docProject
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotli-python=1.1.0=py312hbb81ca0_4
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.10.5=h4c7d964_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312he06e257_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - filelock=3.19.1=pyhd8ed1ab_0
  - freetype=2.14.1=h57928b3_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - intel-openmp=2025.2.0=h57928b3_757
  - jinja2=3.1.6=pyhd8ed1ab_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcblas=3.9.0=12_hb3dda5d_netlib
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=12_h13b7882_netlib
  - liblzma=5.8.1=h2466b09_2
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.50=h7351971_1
  - libsqlite=3.50.4=hf5d6505_0
  - libtiff=4.7.1=h550210a_0
  - libuv=1.51.0=hfd05255_1
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h2466b09_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=3.0.3=py312h05f76fc_0
  - mkl=2023.1.0=h6a75c08_48682
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msys2-conda-epoch=20160418=1
  - networkx=3.5=pyhe01879c_0
  - numpy=2.3.3=py312ha72d056_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.5.4=h725018a_0
  - pillow=10.4.0=py312h381445a_1
  - pip=25.2=pyh8b19718_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.11=h3f84c4b_0_cpython
  - python_abi=3.12=8_cp312
  - pytorch=2.5.1=py3.12_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py312h05f76fc_0
  - requests=2.32.5=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=h18a62a1_3
  - tk=8.6.13=h2c6b04d_2
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - yaml=0.2.5=h6a83c73_3
  - zstandard=0.25.0=py312he5662c2_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - alembic==1.16.5
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - authlib==1.6.5
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - blinker==1.9.0
      - cachetools==6.2.0
      - click==8.3.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.3
      - cryptography==45.0.7
      - cycler==0.12.1
      - cyclopts==3.24.0
      - databricks-sdk==0.67.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dnspython==2.8.0
      - docker==7.1.0
      - docstring-parser==0.17.0
      - docutils==0.22.2
      - email-validator==2.3.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.118.2
      - fastjsonschema==2.21.2
      - fastmcp==2.12.4
      - flask==3.1.2
      - fonttools==4.60.1
      - fqdn==1.5.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.2
      - importlib-metadata==8.7.0
      - ipykernel==6.30.1
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - isodate==0.7.2
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-path==0.3.4
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.9
      - lark==1.3.0
      - lazy-object-proxy==1.12.0
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mcp==1.16.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - mlflow==3.4.0
      - mlflow-skinny==3.4.0
      - mlflow-tracing==3.4.0
      - more-itertools==10.8.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - openapi-core==0.19.5
      - openapi-pydantic==0.5.1
      - openapi-schema-validator==0.6.3
      - openapi-spec-validator==0.7.2
      - opentelemetry-api==1.37.0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parse==1.20.2
      - parso==0.8.5
      - pathable==0.4.4
      - platformdirs==4.4.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==6.32.1
      - psutil==7.1.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pydantic-settings==2.11.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyperclip==1.11.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pywin32==311
      - pywinpty==3.0.2
      - pyzmq==27.1.0
      - referencing==0.36.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.1.0
      - rich-rst==1.3.1
      - rpds-py==0.27.1
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.40.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.43
      - sqlparse==0.5.3
      - sse-starlette==3.0.2
      - stack-data==0.6.3
      - starlette==0.48.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tornado==6.5.2
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20251008
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - uvicorn==0.37.0
      - waitress==3.0.2
      - wandb==0.22.2
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.1
      - zipp==3.23.0
prefix: C:\Users\julia\.conda\envs\docProject
